### ISSUE TITLE
Unable to float text when input is not required

### ISSUE THREAD

**Issue by jchilde** [syncfusion/ej2-react-inputs#2]
Using preview 15.4.17.  
`` <input name={this.props.Id} id={this.props.Id} onBlur={this.props.Callback} type="text" required />``
works, but
`` <input name={this.props.Id} id={this.props.Id} onBlur={this.props.Callback} type="text" />``
does not work.  onBlur does not change things.

**Comment by Eswari89** [comment]
Creating the Text box as a CSS component , we need set the required attribute to the Input element to achieve the floating label functionality which is used for validating the element existence in text box. 

If you want to achieve the floating label functionality without required attribute then you need to manually float the label above of the Input using events such as focus, blur and input. 
Check the below code snippet:

class App extends React.Component<{}, {}> {
  constructor() {
    super();
    this.onFocusOut = this.onFocusOut.bind(this);
    this.onFocusIn = this.onFocusIn.bind(this);
    this.onInputEvt = this.onInputEvt.bind(this);
  }

  onFocusOut(args) {
    /* Update the label position based on Input value */
    this.updateLabelState(args.target.value, args.target.parentElement.querySelector('.e-float-text'));
  }

  onFocusIn(args) {
    let label = args.target.parentElement.querySelector('.e-float-text');
    label.classList.add('e-label-bottom');
   label.classList.remove('e-label-top');
  }
  onInputEvt(args) {
  /* Update the label position based on Input value */
    this.updateLabelState(args.target.value, args.target.parentElement.querySelector('.e-float-text'));
  }
  
  updateLabelState(value,label) {
  /* e-label-top - Float the label above of the Input */
  /* e-label-bottom - Move the label to the Input */
      if (value) {
        label.classList.add('e-label-top');
        label.classList.remove('e-label-bottom');
      } else {
        label.classList.add('e-label-bottom');
        label.classList.remove('e-label-top');
      }
  }
}


render() {
        return (
            <input id='inpt1' type="text" onInput= {this.onInputEvt}  onFocus={this.onFocusIn} onBlur={ this.onFocusOut } />
        )
    }

You can find the sample with floating label input without required attribute using input events. http://plnkr.co/edit/uuz1MxNMECYrNXQdVxqu?p=preview
